services:
  - type: web
    name: owner-app
    env: node
    plan: free
    buildCommand: npm install && npm run build && cd server && npm install --production
    startCommand: cd server && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SLACK_WEBHOOK_URL
        sync: false
    domains:
      - owner-app.onrender.com 