services:
  - type: web
    name: owner-app
    env: node
    plan: free
    buildCommand: npm ci && VITE_BFF_URL=https://owner-app.onrender.com npm run build:no-check && cd server && npm install --only=production
    startCommand: cd server && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SLACK_WEBHOOK_URL
        sync: false 